"use client"

import { useState, useRef, useEffect } from "react"
import { Volume2, VolumeX, Play, Pause, Maximize } from "lucide-react"
import { Button } from "@/components/ui/button"

interface VideoData {
  id: string
  title: string
  src: string
  prompt: string
  description: string
}

const videoData: VideoData[] = [
  {
    id: "1",
    title: "Mountain Explorers Journey",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/20250917_1550_Two%20mountain%20explorers%20in%20bright%20technical%20shells,%20ice%20crusted%20faces,%20eyes%20narrowed%20with%20urgency%20sho_simple_compose_01k5cxxqm3f3as63704h22e6vp%20(1).mp4",
    prompt: "two mountain explorers on an epic journey",
    description:
      "You can also directly inject elements of the real world into Sora 2. For example, by observing a video of one of our teammates, the model can insert them into any Sora-generated environment with an accurate portrayal of appearance and voice. This capability is very general, and works for any human, animal or object.",
  },
  {
    id: "2",
    title: "Cinematic Adventure",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/20250924_2217_New%20Video_simple_compose_01k5zmvgtneqvspy56ark3tt7v%20(1).mp4",
    prompt: "cinematic adventure scene with dramatic lighting",
    description:
      "Experience the thrill of AI-generated cinematic sequences. Sora 2 captures dynamic motion and atmospheric effects with stunning realism, creating immersive storytelling experiences.",
  },
  {
    id: "3",
    title: "Urban Exploration",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/20250929_0337_New%20Video_simple_compose_01k6ags3ztfg8a2xme8kbghq3h%20(1).mp4",
    prompt: "urban exploration with atmospheric depth",
    description:
      "Sora 2 brings environments to life with cinematic lighting and atmospheric effects. Watch as the AI captures energy and mood with incredible detail and photorealistic quality.",
  },
  {
    id: "4",
    title: "Natural Landscapes",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/20250929_2232_New%20Video_simple_compose_01k6chq0nrewsbqkxhnvp77k2y.mp4",
    prompt: "vast natural landscapes with golden hour lighting",
    description:
      "Explore the serene beauty of landscapes generated by Sora 2. The model captures subtle movements and warm lighting with photorealistic quality and cinematic precision.",
  },
  {
    id: "5",
    title: "Dramatic Scenes",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/20250929_2243_New%20Video_simple_compose_01k6cjbphffbwvktsd774srwab.mp4",
    prompt: "dramatic scene with natural lighting and authentic emotion",
    description:
      "Sora 2 excels at generating scenes with authentic emotion and natural lighting. The model understands subtle nuances and atmospheric details that make content feel real and engaging.",
  },
  {
    id: "6",
    title: "Claymation Style",
    src: "https://openaiassets.blob.core.windows.net/$web/nf2/blog-final2/audio/Copy%20of%2020250918_1431_a%20claymation%20conductor%20conducts%20a%20claymation%20orchestra_simple_compose_01k5fbtf2cfrtvxgmj5fv44r02%20(2).mp4",
    prompt: "claymation style animation with tactile textures",
    description:
      "Watch as Sora 2 generates complex scenes with unique artistic styles. The model captures the charm of claymation with tactile textures and coordinated movements.",
  },
]

export function VideoShowcaseSection() {
  const [activeVideoId, setActiveVideoId] = useState(videoData[0].id)
  const [isMuted, setIsMuted] = useState(true)
  const [isPlaying, setIsPlaying] = useState(true)
  const [isTransitioning, setIsTransitioning] = useState(false)
  const [hoveredVideoId, setHoveredVideoId] = useState<string | null>(null)
  const [isHoveringMainVideo, setIsHoveringMainVideo] = useState(false)
  const videoRef = useRef<HTMLVideoElement>(null)
  const thumbnailRefs = useRef<Record<string, HTMLVideoElement | null>>({})
  const playPromisesRef = useRef<Record<string, Promise<void> | null>>({})

  const activeVideo = videoData.find((v) => v.id === activeVideoId) || videoData[0]

  const handleThumbnailClick = (videoId: string) => {
    if (videoId === activeVideoId) return

    setIsTransitioning(true)
    setTimeout(() => {
      setActiveVideoId(videoId)
      setIsTransitioning(false)
    }, 300)
  }

  const togglePlayPause = () => {
    if (videoRef.current) {
      if (videoRef.current.paused) {
        videoRef.current.play()
        setIsPlaying(true)
      } else {
        videoRef.current.pause()
        setIsPlaying(false)
      }
    }
  }

  const toggleMute = () => {
    setIsMuted(!isMuted)
    if (videoRef.current) {
      videoRef.current.muted = !isMuted
    }
  }

  const toggleFullscreen = () => {
    if (videoRef.current) {
      if (!document.fullscreenElement) {
        videoRef.current.requestFullscreen()
      } else {
        document.exitFullscreen()
      }
    }
  }

  const handleThumbnailHover = (videoId: string, isHovering: boolean) => {
    setHoveredVideoId(isHovering ? videoId : null)
    const video = thumbnailRefs.current[videoId]
    if (!video) return

    if (isHovering) {
      // Check if video is ready to play
      if (video.readyState >= 2) {
        // Play and catch all errors including AbortError
        video.play().catch((error) => {
          // Silently handle interruption errors, log others
          if (error.name !== "AbortError") {
            console.error("[v0] Error playing thumbnail video:", error)
          }
        })
      } else {
        // Wait for video to be ready before playing
        const playWhenReady = () => {
          video.play().catch((error) => {
            // Silently handle interruption errors, log others
            if (error.name !== "AbortError") {
              console.error("[v0] Error playing thumbnail video:", error)
            }
          })
          video.removeEventListener("canplay", playWhenReady)
        }
        video.addEventListener("canplay", playWhenReady)
      }
    } else {
      // Pause the video and reset - catch any errors from interrupting play
      try {
        video.pause()
        video.currentTime = 0
      } catch (error) {
        // Silently handle any pause errors
      }
    }
  }

  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.muted = isMuted
    }
  }, [isMuted])

  return (
    <section id="video-showcase" className="w-full py-12 md:py-16 lg:py-24">
      <div className="container mx-auto px-4 md:px-8 lg:px-12">
        {/* Section Header */}
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-4xl md:text-5xl font-semibold text-foreground mb-4">AI-Generated Entertainment</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience the future of content creation with Onepercent's AI-powered video generation platform
          </p>
        </div>

        {/* Main Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6 lg:gap-8 items-start">
          {/* Main Video Player */}
          <div
            className="relative aspect-video w-full rounded-xl overflow-hidden bg-black/60 ring-1 ring-white/10 shadow-cinema-lg"
            onMouseEnter={() => setIsHoveringMainVideo(true)}
            onMouseLeave={() => setIsHoveringMainVideo(false)}
          >
            <div
              className={`absolute inset-0 transition-opacity duration-300 ${isTransitioning ? "opacity-0" : "opacity-100"}`}
            >
              <video
                ref={videoRef}
                src={activeVideo.src}
                className="w-full h-full object-cover"
                autoPlay
                loop
                muted={isMuted}
                playsInline
                aria-describedby="video-info"
              />
            </div>

            <div
              className={`absolute inset-0 pointer-events-none transition-opacity duration-300 ${isHoveringMainVideo ? "opacity-100" : "opacity-0"}`}
            >
              {/* Mute/Unmute Button - Top Right */}
              <Button
                onClick={toggleMute}
                variant="ghost"
                size="icon"
                className="absolute top-4 right-4 bg-black/50 hover:bg-black/70 backdrop-blur-sm text-white rounded-full pointer-events-auto opacity-80 hover:opacity-100 shadow-[0_0_10px_rgba(184,134,11,0.3)] hover:shadow-[0_0_15px_rgba(184,134,11,0.5)] transition-all"
                aria-label={isMuted ? "Unmute video" : "Mute video"}
              >
                {isMuted ? <VolumeX className="w-5 h-5" /> : <Volume2 className="w-5 h-5" />}
              </Button>

              {/* Play/Pause Button - Bottom Center */}
              <Button
                onClick={togglePlayPause}
                variant="ghost"
                size="icon"
                className="absolute bottom-4 left-1/2 -translate-x-1/2 bg-black/50 hover:bg-black/70 backdrop-blur-sm text-white rounded-full pointer-events-auto opacity-80 hover:opacity-100 shadow-[0_0_10px_rgba(184,134,11,0.3)] hover:shadow-[0_0_15px_rgba(184,134,11,0.5)] transition-all"
                aria-label={isPlaying ? "Pause video" : "Play video"}
              >
                {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5 fill-white" />}
              </Button>

              {/* Fullscreen Button - Bottom Right */}
              <Button
                onClick={toggleFullscreen}
                variant="ghost"
                size="icon"
                className="absolute bottom-4 right-4 bg-black/50 hover:bg-black/70 backdrop-blur-sm text-white rounded-full pointer-events-auto opacity-80 hover:opacity-100 shadow-[0_0_10px_rgba(184,134,11,0.3)] hover:shadow-[0_0_15px_rgba(184,134,11,0.5)] transition-all"
                aria-label="Toggle fullscreen"
              >
                <Maximize className="w-5 h-5" />
              </Button>
            </div>
          </div>

          {/* Thumbnails */}
          <div className="flex lg:flex-col gap-3 md:gap-4 overflow-x-auto lg:overflow-y-auto snap-x lg:snap-y snap-mandatory py-2 px-2 lg:px-0 lg:py-2 hide-scrollbar max-h-[600px]">
            {videoData.map((video) => (
              <button
                key={video.id}
                onClick={() => handleThumbnailClick(video.id)}
                onMouseEnter={() => handleThumbnailHover(video.id, true)}
                onMouseLeave={() => handleThumbnailHover(video.id, false)}
                className={`relative flex-shrink-0 w-[200px] lg:w-full aspect-video rounded-xl overflow-hidden snap-center transition-all duration-300 group shadow-md ${
                  video.id === activeVideoId
                    ? "ring-2 ring-[#B8860B]/80 shadow-[0_0_15px_#B8860B40]"
                    : "ring-1 ring-white/10 hover:ring-2 hover:ring-[#C13FFF] hover:shadow-[0_0_15px_rgba(193,63,255,0.3)] hover:brightness-110"
                }`}
                aria-label={`Play ${video.title}`}
                aria-current={video.id === activeVideoId ? "true" : "false"}
              >
                <video
                  ref={(el) => {
                    thumbnailRefs.current[video.id] = el
                  }}
                  src={video.src}
                  className="w-full h-full object-cover"
                  loop
                  muted
                  playsInline
                  preload="metadata"
                />

                {video.id === activeVideoId && (
                  <div className="absolute inset-0 bg-gradient-to-t from-primary/30 to-transparent pointer-events-none" />
                )}
              </button>
            ))}
          </div>
        </div>

        <div
          id="video-info"
          className={`mt-8 md:mt-10 max-w-3xl transition-all duration-500 ${isTransitioning ? "opacity-0 translate-y-2" : "opacity-100 translate-y-0"}`}
        >
          <p className="text-xs md:text-sm text-muted-foreground/70 font-mono uppercase tracking-wider">
            Prompt: {activeVideo.prompt}
          </p>
          <h3 className="mt-3 text-2xl md:text-3xl font-bold bg-gradient-to-r from-primary via-foreground to-foreground bg-clip-text text-transparent">
            {activeVideo.title}
          </h3>
          <p className="mt-3 text-base md:text-lg text-muted-foreground leading-relaxed">{activeVideo.description}</p>
        </div>
      </div>
    </section>
  )
}
